apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatewise-auth
  namespace: gatewise
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-css
    kind: ClusterSecretStore
  target:
    name: gatewise-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  - extract:
      key: /gatewise/auth