apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: gatewise
spec:
  project: default
  source:
    repoURL: https://github.com/lhtran-organization/gatewise-manifests.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gatewise
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    